name: "Build & Release"
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build And Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.2" # 指定最新的稳定版本
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --release --no-tree-shake-icons
      # - run: flutter build ios --release --no-codesign

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

      # 可选：上传到 Google Play
      # - name: Upload Android Release to Play Store
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
      #     packageName: com.example.myapp
      #     releaseFiles: build/app/outputs/apk/release/*.apk
      #     track: production
